name 'minecraft-server'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures minecraft-server'
long_description 'Installs/Configures minecraft-server'
version '0.1.0'
